const ActionTypes = {
  UPDATE_LOADING: "UPDATE_LOADING",
  GET_ITEMS: "GET_ITEMS",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILURE: "GET_ITEMS_FAILURE",
  ITEMS_FILTER_CHANGE: "ITEMS_FILTER_CHANGE",
  CLEAR_ITEMS_LIST: "CLEAR_ITEMS_LIST",
};

export default ActionTypes;
